M48
; DRILL file {KiCad (6.0.4)} date Thu Mar 24 18:37:35 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-24T18:37:35-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X103.3Y-81.94
X103.3Y-87.02
X103.3Y-92.1
T2
X97.91Y-81.62
X97.91Y-92.42
X108.71Y-87.02
T0
M30
